-- Write your models here
CREATE TABLE META_DATA (
    ID  INT(1) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    URL VARCHAR(255) NOT NULL,
    MTD TEXT NOT NULL,
    WITHDRAWAL_STARTS TIME,
    WITHDRAWAL_ENDS   TIME,
    JOB_STARTS        TIME,
    JOB_ENDS          TIME
);

CREATE TABLE USER_ACCOUNT(
    ID   VARCHAR(255) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME  VARCHAR(100) NOT NULL,
    EMAIL      VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255) NOT NULL,
    STATUS     ENUM('OPENED','CLOSED') DEFAULT 'OPENED',
    PLAN       ENUM('STARTER','PREMIUM','UNLIMITED') DEFAULT 'STARTER'
);



CREATE TABLE INVESTOR_ACCOUNT(
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DATE_REGISTERED DATETIME DEFAULT NOW(),
    BALANCE         DECIMAL(12,2),
    CURRENCY        CHAR(7) DEFAULT 'USDT',
    LEVEL           VARCHAR(4),
    VIPs            CHAR(10),
    CREDIT          INT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USER_ACCOUNT(ID) 
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE BASE_ACCOUNT(
    BID    VARCHAR(255) NOT NULL PRIMARY KEY,
    PACCT  VARCHAR(255) NOT NULL,
    CACCT  VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY(PACCT) REFERENCES INVESTOR_ACCOUNT(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE WATCH_LOGS(
    LID VARCHAR(255) NOT NULL PRIMARY KEY,
    ACC_ID VARCHAR(255) NOT NULL,
    PERIOD DATETIME DEFAULT NOW(),
    STATUS ENUM('IN_PROGRESS','COMPLETED') DEFAULT 'IN_PROGRESS',
    FOREIGN KEY(ACC_ID) REFERENCES INVESTOR_ACCOUNT(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE WIDTHDRAWAL_TRANSACTION(
    WID           VARCHAR(255) NOT NULL PRIMARY KEY,
    ACC_ID        VARCHAR(255) NOT NULL,
    AMOUNT        DECIMAL(12,2) NOT NULL,
    DATE_OF_TRAN  DATETIME DEFAULT NOW(),
    STATUS        ENUM('PENDING','COMPLETED') DEFAULT 'PENDING',
    FOREIGN KEY(ACC_ID) REFERENCES INVESTOR_ACCOUNT(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE BOT_LOGS(
    LID VARCHAR(255) NOT NULL PRIMARY KEY,
    LOGS TEXT NOT NULL,
    DATE_ADDED TIMESTAMP(0) NOT NULL
);

INSERT INTO USER_ACCOUNT(ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, STATUS, PLAN)
VALUES('ETUS225372','FIRST NAME HERE','LAST NAME HERE','EMAIL','1234567','OPENED','UNLIMITED');

INSERT INTO INVESTOR_ACCOUNT(ID, USER_ID, USERNAME, PASSWORD, BALANCE,LEVEL, CREDIT)
VALUES('WTU373W7283','ETUS225372','USERNAME HERE','PASSWORD HERE','0.00','Lv.0','5');

